### ISSUE TITLE
Building Code on a New OS

### ISSUE THREAD

**Issue by hollydinkel** [koide3/st_handeye_graph#7]
Hello - is there any chance you could create a Docker image for this repository (and maybe update repository dependencies)? I am having many issues building it on a newer Ubuntu 20.04 OS with python3, OpenCV4, and C++17. If I recall correctly, this worked well on an Ubuntu 18.04 OS with python2, C++11, and OpenCV2. (I used C++11 for the build, but I have several OpenCV version conflicts).
![image](https://github.com/koide3/st_handeye_graph/assets/40707210/bde954cd-adbb-4a57-af90-48e40bd5cfe4)

Error:

```
[ 91%] Built target calibrate
/usr/bin/ld: CMakeFiles/handeye_simulation_xray.dir/src/handeye_simulation_xray.cpp.o: in function `HandeyeSimulationXray::visualize(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, int) const [clone .constprop.0]':
handeye_simulation_xray.cpp:(.text+0x456): undefined reference to `cv::imshow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&)'
/usr/bin/ld: CMakeFiles/handeye_simulation_xray.dir/src/handeye_simulation_xray.cpp.o: in function `main':
handeye_simulation_xray.cpp:(.text.startup+0x2aa9): undefined reference to `cv::imshow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&)'
/usr/bin/ld: handeye_simulation_xray.cpp:(.text.startup+0x3889): undefined reference to `cv::imshow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/handeye_simulation_xray.dir/build.make:157: handeye_simulation_xray] Error 1
make[1]: *** [CMakeFiles/Makefile2:198: CMakeFiles/handeye_simulation_xray.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Comment by hollydinkel** [comment]
I managed to successfully build the package and run the calibration code on the example data by removing `src/handeye_simulation_xray.cpp` and `src/handeye_simulation.cpp`, commenting out lines 61-94 of `CMakeLists.txt`, and commenting out everything after the first `command` in `run_calibration.sh`. I am using OpenCV 3.4 and cmake version 2.8.12 with c++11.
